developmentMode: true
defaultGamemode: 0
maxPlayers: 100
minPlayers: 3

maps:
  waitingRoomMap:
    name: "waitingRoom"
    safeSpawn: "0:100:0"
    exitEntitySpawn: "0:100:0"
    pedestalCenterSpawn: "0:100:0"
    pedestalOneSpawn: "0:100:0"
    pedestalTwoSpawn: "0:100:0"
    pedestalThreeSpawn: "0:100:0"
  roomMap:
    name: "squidgame"
    safeSpawn: "0:100:0"
  greenLightRedLightMap:
    name: "squidGame"
    safeSpawn: "0:100:0"
    goalCornerOne: "0:100:0"
    goalCornerTwo: "0:100:0"
    dollPosition: "0:100:0"
  sugarHoneycombsMap:
    name: "squidGame"
    safeSpawn: "0:100:0"
    spawns:
      "1": "0:100:0"
      "2": "0:100:0"
      "3": "0:100:0"
      "4": "0:100:0"
      "5": "0:100:0"
      "6": "0:100:0"