developmentMode: true
maxPlayers: 100
minPlayers: 3

maps:
  waitingRoomMap:
    name: "waitingRoom"
    safeSpawn: "0:100:0"
    exitEntitySpawn: "0:100:0"
    pedestalCenterSpawn: "0:100:0"
    pedestalOneSpawn: "0:100:0"
    pedestalTwoSpawn: "0:100:0"
    pedestalThreeSpawn: "0:100:0"
  roomMap:
    name: "squidgame"
    safeSpawn: "0:100:0"
  greenLightRedLightMap:
    name: "squidGame"
    safeSpawn: "0:100:0"
    goalCornerOne: "0:100:0"
    goalCornerTwo: "0:100:0"
    dollPosition: "0:100:0"
  sugarHoneycombsMap:
    name: "squidGame"
    safeSpawn: "0:100:0"
    spawns:
      "1": "0:100:0"
      "2": "0:100:0"
      "3": "0:100:0"
      "4": "0:100:0"
      "5": "0:100:0"
      "6": "0:100:0"
  tugOfWarMap:
    name: "squidGame"
    safeSpawn: "0:100:0"
    red:
      spawns:
      "1": "0:100:0"
      "2": "0:100:0"
      "3": "0:100:0"
      "4": "0:100:0"
      "5": "0:100:0"
      "6": "0:100:0"
    blue:
      spawns:
        "1": "0:100:0"
        "2": "0:100:0"
        "3": "0:100:0"
        "4": "0:100:0"
        "5": "0:100:0"
        "6": "0:100:0"
  marblesMap:
    name: "squidGame"
    safeSpawn: "0:100:0"
    odd:
      cornerOne: "0:1000"
      cornerTwo: "0:100:0"
    pair:
      cornerOne: "0:100:0"
      cornerTwo: "0:!00:0"
  hopscotchMap:
    name: "squidGame"
    safeSpawn: "0:100:0"
    crystal:
      number: 10
      sections:
        "1":
          - "0:100:0"
          - "0:100:0"
        "2":
          - "0:100:0"
          - "0:100:0"
        "3":
          - "0:100:0"
          - "0:100:0"
        "4":
          - "0:100:0"
          - "0:100:0"
        "5":
          - "0:100:0"
          - "0:100:0"
        "6":
          - "0:100:0"
          - "0:100:0"
        "7":
          - "0:100:0"
          - "0:100:0"
        "8":
          - "0:100:0"
          - "0:100:0"
        "9":
          - "0:100:0"
          - "0:100:0"
        "10":
          - "0:100:0"
          - "0:100:0"
    goal:
      cornerOne: "0:100:0"
      cornerTwo: "0:100:0"